#!/bin/bash

if [ -n "$1" ]
then
	sensor=$1
else
	echo "no sensor type defined. usage: plot_velocity SensorType [window time]"
fi
if [ -n "$2" ]
then
	T=$2
else
	T=20
fi

echo " ### plotting velocities x y z [m/s] ###"
echo " ### buffer = " $T "sec"

rxplot $sensor/state_out/data[3]:data[4]:data[5] -b $T -t "velocity" -l x,y,z 
