#!/bin/bash

if [ -n "$1" ]
then
	sensor=$1
else
	echo "no sensor type defined. usage: plot_qvw SensorType [window time]"
fi
if [ -n "$2" ]
then
	T=$2
else
	T=20
fi

echo " ### plotting vision-world drift qw qx qy qz [quat] ###"
echo " ### buffer = " $T "sec"

rxplot $sensor/state_out/data[17]:data[18]:data[19]:data[20] -b $T -t "q_vw" -l w,x,y,z 
