#!/bin/bash

if [ -n "$1" ]
then
	sensor=$1
else
	echo "no sensor type defined. usage: plot_scale SensorType [window time]"
fi
if [ -n "$2" ]
then
	T=$2
else
	T=20
fi

echo " ### plotting scale ###"
echo " ### buffer = " $T "sec"

rxplot $sensor/state_out/data[16] -b $T -t "scale" -l L 
