#!/bin/bash

if [ -n "$1" ]
then
	sensor=$1
else
	echo "no sensor type defined. usage: plot_attitude SensorType [window time]"
fi
if [ -n "$2" ]
then
	T=$2
else
	T=20
fi

echo " ### plotting attitude qw qx qy qz [quat] ###"
echo " ### buffer = " $T "sec"

rxplot $sensor/state_out/data[6]:data[7]:data[8]:data[9] -b $T -t "attitude" -l w,x,y,z 
